### ISSUE TITLE
Criar Casos de Teste para cada End-point: Login

### ISSUE THREAD

**Issue by Igorxp5** [Igorxp5/AppLada#30]
Utilizando o Cucumber criar os casos de teste para cada um dos end-points propostos (aguardar conclusão da tarefa #28), e criar usando o RSpec.

**Comment by Galtvam** [comment]
Lista de testes do desenvolvidos para o Login:

para o campo de username (pode conter o username ou email)

        sucesso:
            username e senha corretos
            email e senha corretos
        
        falha:
            username inexistente
            email inexistente
            campo vazio
        
   para o campo de password
        
        falha:
            username correto com senha errada
            email correto com senha errada
            campo vazio

**Comment by Galtvam** [comment]
Lista de testes do endpoint de Login:
   
para o campo de username( pode conter um username ou email).
        
        sucesso (retornam token):
            campo username (preenchido com um username) e senha corretos
            campo username (preenchido com um email) e senha corretos
        
        falha (retornam erro):
            campo com username inexistente
            campo com email inexistente
            campo vazio
        
   para o campo de password
        
        falha (retornam erro):
            campo username (preenchido com um username) correto com senha errada
            campo username (preenchido com um email) correto com senha errada
            campo vazio
