### ISSUE TITLE
Criar Casos de Teste para cada End-point: Cadastro

### ISSUE THREAD

**Issue by Igorxp5** [Igorxp5/AppLada#33]
Utilizando o Cucumber criar os casos de teste para cada um dos end-points propostos (aguardar conclusão da tarefa #28), e criar usando o RSpec.

**Comment by Galtvam** [comment]
Lista de testes do endpoint de Cadastro:
campos [username, password, name, email, birthday, gender]
    
    Sucesso (retorna username e senha):
        username, password, name, email, birthday e gender corretos
    
    
para o campo de username:
        
        falha (retorna erro):
            username já utilizado
            campo vazio
        
para o campo de password:
    
        falha (retorna erro):
            campo vazio
        
para o campo de name:

        falha (retorna erro):
            campo vazio
        
para o campo de email:

        falha (retorna erro):
            email já utilizado
            campo vazio
        
para o campo de brithday:

        falha (retorna erro):
            campo vazio
            
para o campo de gender:

        falha (retorna erro):
            campo vazio
