### ISSUE TITLE
Design da Tela de Dashboard - Jogar

### ISSUE THREAD

**Issue by lucaspcburgos** [Igorxp5/AppLada#65]
Design das telas da parte de jogar:
  - Procurar uma pelada
  - Criar uma pelada

**Comment by Igorxp5** [comment]
![Dashboard - Encontrar  Pelada](https://user-images.githubusercontent.com/8163093/66718377-966d7800-edb9-11e9-8533-257d55264985.png)

**Comment by Igorxp5** [comment]
Todas as telas estão sendo mapeadas no Adobe XD neste link: https://xd.adobe.com/view/ec8d9a0c-c6a4-4d58-6c0a-f38d2b6579a8-9abc/screen/5441485c-793a-4476-be47-ba4b53917c82/Dashboard-Perfil-Feed?hints=off

**Comment by Igorxp5** [comment]
O protótipo da aplicação em Adobe XD pode ser encontrado neste link: https://xd.adobe.com/view/3d26c1f8-ebf0-4cca-77f9-f7f0710c9a4a-4b17/?fullscreen&hints=off
