### ISSUE TITLE
Design da Tela de Dashboard - Perfil

### ISSUE THREAD

**Issue by lucaspcburgos** [Igorxp5/AppLada#66]
Fazer o design da tela de perfil do usuário, onde ele irá poder configurar suas informações.

**Comment by Igorxp5** [comment]
Não tem informações alteráveis nas telas montadas.

**Comment by Igorxp5** [comment]
![Dashboard - Perfil - Feed](https://user-images.githubusercontent.com/8163093/66726511-32c26980-ee10-11e9-8ce2-54ee6c13615f.png)

**Comment by Igorxp5** [comment]
O protótipo da aplicação em Adobe XD pode ser encontrado neste link: https://xd.adobe.com/view/3d26c1f8-ebf0-4cca-77f9-f7f0710c9a4a-4b17/?fullscreen&hints=off
