### ISSUE TITLE
Desenvolver Teste para a Tela de Login, Cadastro e Recuperação de Senha

### ISSUE THREAD

**Issue by Igorxp5** [Igorxp5/AppLada#77]
Utilizar o cypress para desenvolver os testes para as telas de de login, cadastro e recuperação de senha. O teste deve seguir ideia de fluxo passada na issue #75.

**Comment by KayqueSantos** [comment]
Testes escritos utilizando linguagem declarativa e explícita. Os mesmos podem ser acessados em #82

**Comment by KayqueSantos** [comment]
Próximo passo, escrever testes usando Cypress.

**Comment by KayqueSantos** [comment]
Testes escritos em Cypress. Ver #84
